---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :audit_only

platforms:
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[audit::default]
    attributes:
